ojs_citation_new:
    path:     /{journalId}/article/{articleId}/advanced-citation/new
    defaults: { _controller: "OjsCitationBundle:Citation:new" }

ojs_citation_create:
    path:     /{journalId}/article/{articleId}/advanced-citation/create
    defaults: { _controller: "OjsCitationBundle:Citation:create" }
    methods:  [POST]

ojs_citation_edit:
    path:     /{journalId}/article/{articleId}/advanced-citation/{id}/edit
    defaults: { _controller: "OjsCitationBundle:Citation:edit" }

ojs_citation_update:
    path:     /{journalId}/article/{articleId}/advanced-citation/{id}/update
    defaults: { _controller: "OjsCitationBundle:Citation:update" }
    methods:  [PUT]

ojs_citation_rest_parse:
    path:     /citations-to-form/
    defaults: { _controller: "OjsCitationBundle:Citation:citationsToForm" }
    methods:  [POST]
