services:
  advanced_citation.routing_loader:
    class: OkulBilisim\AdvancedCitationBundle\Routing\AdvancedLoader
    tags:
      - { name: routing.loader }
  advanced_citation.citation_subscriber:
      class: OkulBilisim\AdvancedCitationBundle\EventListener\CitationEventSubscriber
      tags:
          - { name: doctrine.event_subscriber, connection: default }