services:
  advanced_citation.citation_subscriber:
      class: BulutYazilim\AdvancedCitationBundle\EventListener\CitationEventSubscriber
      arguments: ["@router", "@doctrine.orm.entity_manager"]
      tags:
          - { name: kernel.event_subscriber }
  advanced_citation.twig_subscriber:
      class: BulutYazilim\AdvancedCitationBundle\EventListener\TwigEventSubscriber
      arguments: ["@doctrine.orm.entity_manager", "@twig", "%kernel.root_dir%"]
      tags:
          - { name: kernel.event_subscriber }
